apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-frontend
  namespace: comp-math
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab2-frontend
  template:
    metadata:
      labels:
        app: lab2-frontend
    spec:
      containers:
      - name: lab2-frontend-container
        image: artem5252/cm-2-frontend:latest
        ports:
        - containerPort: 3000