  apiVersion: v1
  kind: Service
  metadata:
    name: lab2-frontend-service
    namespace: comp-math
  spec:
    selector:
      app: lab2-frontend
    ports:
    - port: 80      
      targetPort: 3000
    type: ClusterIP