apiVersion: v1
kind: Secret
metadata:
  name: lab4-secrets
  namespace: lab4
type: Opaque
stringData:
  DB_USERNAME: admin
  DB_PASSWORD: admin
  DB_NAME: lab4
  JWT_SECRET_KEY: your-super-secret-jwt-key-change-me
  DATABASE_URL: jdbc:postgresql://postgres-service:5432/lab4