apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-backend
  namespace: comp-math
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab2-backend
  template:
    metadata:
      labels:
        app: lab2-backend
    spec:
      containers:
        - name: lab2-backend-container
          image: artem5252/cm-2-backend:latest
          ports:
            - containerPort: 8080